"""WebUI route inventory (Task 18).

The admin server is being split into per-domain route modules; this snapshot is
what makes that split provably behaviour-preserving — every route the
single-file server served must still be served afterwards, and nothing may
appear or vanish silently. Route *handlers* may move between modules freely:
the table is method + path only.
"""

from __future__ import annotations

import socket

ROUTES = [
    "DELETE /api/v1/ai/models/{name}",
    "DELETE /api/v1/ai/providers/{name}",
    "DELETE /api/v1/credentials/{domain}/{ref}",
    "DELETE /api/v1/session",
    "DELETE /api/v1/tools/permissions",
    "GET /",
    "GET /agent",
    "GET /agent/metrics",
    "GET /agent/policy",
    "GET /agent/simulator",
    "GET /agent/tasks",
    "GET /agent/tasks/{task_id}",
    "GET /api/v1/agent",
    "GET /api/v1/agent/tasks",
    "GET /api/v1/agent/tasks/{task_id}",
    "GET /api/v1/ai/models",
    "GET /api/v1/ai/providers",
    "GET /api/v1/ai/roles",
    "GET /api/v1/ai/status",
    "GET /api/v1/ai/usage",
    "GET /api/v1/character",
    "GET /api/v1/character/export",
    "GET /api/v1/character/state",
    "GET /api/v1/config/effective",
    "GET /api/v1/config/raw",
    "GET /api/v1/config/restart-pending",
    "GET /api/v1/config/schema",
    "GET /api/v1/credentials",
    "GET /api/v1/csrf",
    "GET /api/v1/expressions",
    "GET /api/v1/logs/channels",
    "GET /api/v1/logs/tail",
    "GET /api/v1/memories",
    "GET /api/v1/memories/consolidation",
    "GET /api/v1/memories/embeddings",
    "GET /api/v1/memories/health",
    "GET /api/v1/memories/retrieval-debug",
    "GET /api/v1/memories/timeline",
    "GET /api/v1/memories/{memory_id}",
    "GET /api/v1/meta",
    "GET /api/v1/minecraft",
    "GET /api/v1/minecraft/inventory",
    "GET /api/v1/minecraft/inventory/slots",
    "GET /api/v1/minecraft/memory",
    "GET /api/v1/minecraft/task",
    "GET /api/v1/minecraft/task/{task_id}",
    "GET /api/v1/minecraft/world",
    "GET /api/v1/overview",
    "GET /api/v1/prompts",
    "GET /api/v1/runtime",
    "GET /api/v1/runtime/scheduler",
    "GET /api/v1/runtime/status",
    "GET /api/v1/session",
    "GET /api/v1/social/commitments",
    "GET /api/v1/social/commitments/{commitment_id}",
    "GET /api/v1/social/groups",
    "GET /api/v1/social/overview",
    "GET /api/v1/social/relationships",
    "GET /api/v1/social/sessions",
    "GET /api/v1/social/spaces",
    "GET /api/v1/social/users",
    "GET /api/v1/social/users/{person_id}",
    "GET /api/v1/stickers",
    "GET /api/v1/tools",
    "GET /api/v1/tools/decision-debug",
    "GET /api/v1/tools/executions",
    "GET /api/v1/tools/metrics",
    "GET /api/v1/tools/permissions",
    "GET /api/v1/tools/{name}",
    "GET /api/v1/world",
    "GET /api/v1/world/activity",
    "GET /api/v1/world/activity/advisor",
    "GET /api/v1/world/activity/decision",
    "GET /api/v1/world/activity/plan",
    "GET /api/v1/world/agent-plans",
    "GET /api/v1/world/initiative",
    "GET /api/v1/world/proposals",
    "GET /api/v1/world/timeline",
    "GET /api/v1/world/topics",
    "GET /api/v1/world/trace",
    "GET /assets/{tail}",
    "GET /behavior",
    "GET /character",
    "GET /character",
    "GET /character/export",
    "GET /config",
    "GET /conversation",
    "GET /conversation/continuity",
    "GET /credentials",
    "GET /expressions",
    "GET /favicon.ico",
    "GET /groups",
    "GET /legacy",
    "GET /legacy/character",
    "GET /legacy/memory",
    "GET /legacy/memory/health",
    "GET /legacy/memory/timeline",
    "GET /legacy/social",
    "GET /login",
    "GET /logs",
    "GET /memory",
    "GET /memory",
    "GET /memory/consolidation",
    "GET /memory/correction",
    "GET /memory/detail/{memory_id}",
    "GET /memory/embeddings",
    "GET /memory/health",
    "GET /memory/health",
    "GET /memory/retrieval-debug",
    "GET /memory/search",
    "GET /memory/timeline",
    "GET /memory/timeline",
    "GET /models",
    "GET /prompts",
    "GET /runtime",
    "GET /sandbox",
    "GET /sandbox/bible",
    "GET /sandbox/chat",
    "GET /sandbox/inspectors",
    "GET /sandbox/needs",
    "GET /sandbox/trace",
    "GET /sessions",
    "GET /social",
    "GET /social",
    "GET /social/group",
    "GET /social/observations",
    "GET /social/policy",
    "GET /social/simulator",
    "GET /stickers",
    "GET /tools",
    "GET /tools/decision-debug",
    "GET /tools/executions",
    "GET /tools/metrics",
    "GET /tools/permissions",
    "GET /tools/{name}",
    "GET /topics",
    "GET /users",
    "GET /ws/events",
    "GET /{tail}",
    "PATCH /api/v1/character",
    "PATCH /api/v1/character/state",
    "PATCH /api/v1/config",
    "PATCH /api/v1/prompts",
    "PATCH /api/v1/session",
    "PATCH /api/v1/social/groups/{group_id}",
    "PATCH /api/v1/social/users/{person_id}",
    "PATCH /api/v1/tools/{name}",
    "POST /agent/simulator",
    "POST /api/agent/control",
    "POST /api/credentials",
    "POST /api/credentials/delete",
    "POST /api/memory/{action}/{memory_id}",
    "POST /api/models/override",
    "POST /api/runtime/{action}",
    "POST /api/sandbox/control",
    "POST /api/sessions/clear",
    "POST /api/stickers/reindex",
    "POST /api/stickers/{action}/{sticker_id}",
    "POST /api/tools/cache/clear",
    "POST /api/tools/config",
    "POST /api/tools/permission",
    "POST /api/tools/permission/clear",
    "POST /api/tools/test",
    "POST /api/tools/toggle",
    "POST /api/topics/{action}/{topic_id}",
    "POST /api/v1/agent/simulate",
    "POST /api/v1/agent/tasks/{task_id}/{action}",
    "POST /api/v1/ai/models/{name}/test",
    "POST /api/v1/ai/router/reset",
    "POST /api/v1/behavior/preview",
    "POST /api/v1/behavior/test-response",
    "POST /api/v1/behavior/triggers/{action}",
    "POST /api/v1/character/import",
    "POST /api/v1/config/reset",
    "POST /api/v1/config/validate",
    "POST /api/v1/credentials/test",
    "POST /api/v1/expressions/{pattern_id}/{action}",
    "POST /api/v1/memories/consolidation/run",
    "POST /api/v1/memories/embeddings/{action}",
    "POST /api/v1/memories/{memory_id}/{action}",
    "POST /api/v1/minecraft/agent/confirm",
    "POST /api/v1/minecraft/container_inspect",
    "POST /api/v1/minecraft/container_transfer",
    "POST /api/v1/minecraft/craft",
    "POST /api/v1/minecraft/dig",
    "POST /api/v1/minecraft/dig_capability",
    "POST /api/v1/minecraft/dropped_items",
    "POST /api/v1/minecraft/equip",
    "POST /api/v1/minecraft/events",
    "POST /api/v1/minecraft/find_blocks",
    "POST /api/v1/minecraft/follow_player",
    "POST /api/v1/minecraft/inventory_move",
    "POST /api/v1/minecraft/join",
    "POST /api/v1/minecraft/leave",
    "POST /api/v1/minecraft/look_at",
    "POST /api/v1/minecraft/move_to",
    "POST /api/v1/minecraft/pickup_item",
    "POST /api/v1/minecraft/place",
    "POST /api/v1/minecraft/recipe_lookup",
    "POST /api/v1/minecraft/stop",
    "POST /api/v1/minecraft/task/{task_id}/{action}",
    "POST /api/v1/runtime/actions/{name}",
    "POST /api/v1/runtime/tick",
    "POST /api/v1/session",
    "POST /api/v1/session/password",
    "POST /api/v1/sessions/{session_id}/clear",
    "POST /api/v1/stickers/reindex",
    "POST /api/v1/stickers/{sticker_id}/{action}",
    "POST /api/v1/tools/cache/clear",
    "POST /api/v1/tools/{name}/test",
    "POST /api/v1/world/control/{action}",
    "POST /api/v1/world/topics/{topic_id}/{action}",
    "POST /behavior/preview",
    "POST /behavior/settings",
    "POST /behavior/test-response",
    "POST /behavior/trigger/{action}",
    "POST /character",
    "POST /character/import",
    "POST /character/import/confirm",
    "POST /character/state",
    "POST /config/ai",
    "POST /config/basic",
    "POST /config/onebot",
    "POST /config/raw",
    "POST /config/reset",
    "POST /config/test-provider",
    "POST /config/web",
    "POST /expressions/delete",
    "POST /expressions/toggle",
    "POST /groups/toggle",
    "POST /legacy/character",
    "POST /login",
    "POST /logout",
    "POST /memory/consolidation/run",
    "POST /memory/correction",
    "POST /memory/correction/apply",
    "POST /memory/embeddings/{action}",
    "POST /memory/retrieval-debug",
    "POST /memory/search",
    "POST /prompts",
    "POST /sandbox/simulate",
    "POST /social/analyze",
    "POST /social/policy",
    "POST /social/replay",
    "POST /tools/decision-debug",
    "POST /users",
    "PUT /api/v1/ai/models/order",
    "PUT /api/v1/ai/models/{name}",
    "PUT /api/v1/ai/providers/{name}",
    "PUT /api/v1/ai/roles/{role}",
    "PUT /api/v1/config/raw",
    "PUT /api/v1/credentials/{domain}/{ref}",
    "PUT /api/v1/tools/permissions",
]


class TestRouteInventory:
    async def test_admin_route_table_matches_the_snapshot(self, tmp_path) -> None:
        from app.config.settings import AppConfig
        from app.core.bot import Bot
        from app.web.server import WebServer
        from tests.test_web_realtime import DummyAdapter

        with socket.socket() as probe:
            probe.bind(("127.0.0.1", 0))
            port = int(probe.getsockname()[1])
        config = AppConfig(
            bot={"name": "TestBot"},
            database={"url": "sqlite:///" + str(tmp_path / "routes.db")},
            logging={"log_dir": str(tmp_path / "logs")},
            web={
                "enabled": True,
                "host": "127.0.0.1",
                "port": port,
                "username": "admin",
                "password": "pw123",
            },
        )
        bot = Bot(config, DummyAdapter())
        await bot.database.connect()
        await bot.character.start()
        server = WebServer(config.web, bot)
        await server.start()
        try:
            table = sorted(
                f"{route.method} {route.resource.canonical}"
                for route in server._runner.app.router.routes()
                if route.method not in ("HEAD",)
            )
        finally:
            await server.stop()
            await bot.shutdown()

        assert table == ROUTES, (
            "WebUI 路由表与快照不一致："
            f" 新增: {sorted(set(table) - set(ROUTES))} / 丢失: {sorted(set(ROUTES) - set(table))}"
        )
