"""Experience layer (v2.1 Phase 4 §5-§7): what she actually lived through.

    SandboxEvent → ExperienceBuilder → ExperienceRecord

Experiences are derived from *real* sandbox events only — never generated by
an LLM (§6/§14). The builder is deliberately selective (§7 noise filter):

* business events (action completed/interrupted/resumed, interactions, pet
  fed, external influence, project milestones, first-time knowledge) become
  experiences;
* continuous noise (NEED_CHANGED drift, request/started bookkeeping, routine
  queue traffic) is ignored;
* one behaviour chain (same ``correlation_id``) collapses into **one**
  experience — the pet-feed chain must not produce five near-duplicate rows.

Importance is a deterministic score (§13) computed from the event kind and
its payload; it decides whether the experience can later become a memory
candidate, not whether it is remembered as an experience.
"""

from __future__ import annotations

import uuid
from collections import deque
from enum import Enum
from typing import Any

from pydantic import BaseModel, Field

from app.sandbox.commitments import MIN_FULFILL_DURATION_MINUTES
from app.sandbox.events import SandboxEvent
from app.sandbox.events import SandboxEventType as ET

#: events that may carry experience meaning (§7) — an allow-list, not a
#: deny-list, so new internal events never leak into memory by accident
EXPERIENCE_EVENTS: frozenset[ET] = frozenset(
    {
        ET.ACTION_COMPLETED,
        ET.ACTION_INTERRUPTED,
        ET.ACTION_RESUMED,
        ET.INTERACTION_COMPLETED,
        ET.PET_FED,
        ET.PROJECT_PROGRESS_CHANGED,
        ET.KNOWLEDGE_CHANGED,
        ET.WORLD_EXTERNAL_INFLUENCE,
        ET.SOCIAL_SPACE_CHANGED,
        #: §20: a completed goal may become a memory; creation never does
        ET.GOAL_COMPLETED,
        #: Phase 10 §4/§5: a verified shared activity is a *shared episode* —
        #: other social facts are handled by their own layers, never here
        ET.SOCIAL_INTERACTION,
    }
)

#: events that carry experience meaning only under a payload condition, and
#: the significance values that qualify. A relationship change is an experience
#: when it crossed a milestone (§27); ordinary trust 0.50 → 0.51 must never
#: pollute memory. A commitment *outcome* is an experience (§32) — creating a
#: commitment is not.
CONDITIONAL_SIGNIFICANCE: dict[ET, frozenset[str]] = {
    ET.RELATIONSHIP_CHANGED: frozenset({"major"}),
    ET.COMMITMENT_FULFILLED: frozenset({"meaningful", "major"}),
    ET.COMMITMENT_BROKEN: frozenset({"meaningful", "major"}),
    ET.COMMITMENT_RESCHEDULED: frozenset({"major"}),
}
#: kept for existing callers: every conditionally-experienced event
CONDITIONAL_EXPERIENCE_EVENTS: frozenset[ET] = frozenset(CONDITIONAL_SIGNIFICANCE)

#: §9 (Phase 10): a shared episode's importance is a fixed ladder —
#: reaching the minimum duration makes it an *experience*; only social
#: weight (a promise kept, a long session, major significance) makes it a
#: long-term memory. No dice, no model, no hidden scoring system.
SHARED_ACTIVITY_BASE_IMPORTANCE = 0.4
SHARED_COMMITMENT_BONUS = 0.25  # this was a promise actually kept
SHARED_LONG_MINUTES = 60.0  # a session this long is worth a little more
SHARED_LONG_BONUS = 0.05
SHARED_MAJOR_BONUS = 0.15  # the fact itself was verified as major

#: project progress thresholds that count as milestones (§22/§28-6)
PROJECT_MILESTONES = (0.5, 0.75, 1.0)


class ExperienceKind(str, Enum):  # noqa: UP042 - pydantic-friendly str enum
    action_completed = "action_completed"
    action_interrupted = "action_interrupted"
    action_resumed = "action_resumed"
    interaction_completed = "interaction_completed"
    pet_care = "pet_care"
    project_milestone = "project_milestone"
    knowledge_learned = "knowledge_learned"
    external_influence = "external_influence"
    social_contact = "social_contact"
    goal_completed = "goal_completed"
    relationship_changed = "relationship_changed"
    #: Phase 9 §32: a promise kept / missed / moved — never its mere creation
    commitment_outcome = "commitment_outcome"
    #: Phase 10 §4: a real episode lived *with* someone (verified shared activity)
    shared_activity = "shared_activity"


class ExperienceRecord(BaseModel):
    """One lived-through episode (§5) with full event provenance."""

    id: str
    character_id: str = ""
    timestamp: float = 0.0
    kind: ExperienceKind
    summary: str = ""
    importance: float = Field(default=0.3, ge=0.0, le=1.0)
    location: str = ""
    actors: list[str] = Field(default_factory=list)
    #: every sandbox event id that fed this record (provenance root, §10)
    source_event_ids: list[str] = Field(default_factory=list)
    causation_id: str = ""
    correlation_id: str = ""
    action_id: str = ""
    interaction_type: str = ""
    external_source: str = ""
    metadata: dict[str, Any] = Field(default_factory=dict)


def _milestone_crossed(before: float, after: float) -> bool:
    return any(before < mark <= after for mark in PROJECT_MILESTONES)


class ExperienceBuilder:
    """Event-bus subscriber turning sandbox facts into ExperienceRecords.

    One record per behaviour chain: repeat observations of the same
    ``correlation_id`` merge into the existing record (its ``importance``
    takes the maximum, its kind is upgraded by the priority table below).
    """

    #: higher rank wins when a chain produces several qualifying events
    _KIND_RANK = {
        ExperienceKind.social_contact: 1,
        # §7: the shared episode absorbs the action/promise pieces of its chain
        ExperienceKind.shared_activity: 20,
        ExperienceKind.action_resumed: 2,
        ExperienceKind.interaction_completed: 3,
        ExperienceKind.action_completed: 4,
        ExperienceKind.knowledge_learned: 5,
        ExperienceKind.pet_care: 6,
        ExperienceKind.project_milestone: 7,
        ExperienceKind.action_interrupted: 8,
        ExperienceKind.external_influence: 9,
    }

    def __init__(self, runtime: Any, *, clock: Any) -> None:
        self._rt = runtime
        self._clock = clock
        self._pending: list[ExperienceRecord] = []
        #: audit trail of everything emitted (replay/dedupe tests, continuity)
        self._emitted: deque[ExperienceRecord] = deque(maxlen=128)
        self._by_correlation: dict[str, ExperienceRecord] = {}
        #: §7/§12: episode identity — the same real act (ActionInstance, or a
        #: commitment) must stay *one* record even across different threads
        self._by_episode: dict[str, ExperienceRecord] = {}
        self.ignored = 0

    # ------------------------------------------------------------------ bus

    def observe(self, event: SandboxEvent) -> None:
        """Bus handler (sync): qualifying event → experience in the buffer."""
        if event.event_type in CONDITIONAL_SIGNIFICANCE:
            allowed = CONDITIONAL_SIGNIFICANCE[event.event_type]
            if str(event.payload.get("significance", "")) not in allowed:
                self.ignored += 1  # ordinary drift is not an experience (§27)
                return
        elif event.event_type not in EXPERIENCE_EVENTS:
            self.ignored += 1
            return
        built = self._build(event)
        if built is None:
            self.ignored += 1
            return
        kind, summary, importance, metadata = built
        key = event.correlation_id or event.event_id
        existing = self._by_correlation.get(key)
        if existing is None:
            # §7: the same ActionInstance / commitment is the same lived act,
            # even when the events arrive on different threads
            existing = next(
                (
                    self._by_episode[episode]
                    for episode in self._episode_keys(metadata)
                    if episode in self._by_episode
                ),
                None,
            )
        if existing is not None:
            self._absorb(existing, event, kind, summary, importance, metadata)
            self._by_correlation[key] = existing  # the new thread belongs to it too
            return
        record = ExperienceRecord(
            id=f"exp_{uuid.uuid4().hex[:12]}",
            character_id=getattr(self._rt, "character_id", ""),
            timestamp=float(event.timestamp or self._clock()),
            kind=kind,
            summary=summary,
            importance=importance,
            location=self._rt.character.location,
            actors=[actor for actor in (event.source_entity_id, event.target_entity_id) if actor],
            source_event_ids=[event.event_id],
            causation_id=event.causation_id,
            correlation_id=event.correlation_id,
            action_id=str(event.payload.get("action_id", "") or ""),
            interaction_type=str(event.payload.get("interaction_type", "") or ""),
            external_source=str(event.payload.get("source", "") or ""),
            metadata=metadata,
        )
        self._by_correlation[key] = record
        for episode in self._episode_keys(metadata):
            self._by_episode.setdefault(episode, record)
        self._pending.append(record)
        self._emitted.append(record)

    @staticmethod
    def _episode_keys(metadata: dict[str, Any]) -> list[str]:
        """Episode identity for a built record: instance > commitment (§4/§12)."""
        keys: list[str] = []
        instance_id = str(metadata.get("action_instance_id", "") or "")
        if instance_id:
            keys.append(f"action:{instance_id}")
        commitment_id = str(metadata.get("commitment_id", "") or "")
        if commitment_id:
            keys.append(f"commitment:{commitment_id}")
        interaction_id = str(metadata.get("interaction_id", "") or "")
        if interaction_id:
            keys.append(f"interaction:{interaction_id}")  # replay of the same fact
        return keys

    def _absorb(
        self,
        record: ExperienceRecord,
        event: SandboxEvent,
        kind: ExperienceKind,
        summary: str,
        importance: float,
        metadata: dict[str, Any],
    ) -> None:
        """Fold one more fact of the same episode into the existing record (§7)."""
        if event.event_id not in record.source_event_ids:
            record.source_event_ids.append(event.event_id)
        record.importance = max(record.importance, importance)
        if self._KIND_RANK.get(kind, 0) > self._KIND_RANK.get(record.kind, 0):
            record.kind = kind
            record.summary = summary
        record.metadata.update(metadata)
        if not record.action_id:
            record.action_id = str(event.payload.get("action_id", "") or "")
        instance_id = str(metadata.get("action_instance_id", "") or "")
        if instance_id:
            self._by_episode.setdefault(f"action:{instance_id}", record)

    # ------------------------------------------------------------ mapping

    def _shared_activity(
        self, event: SandboxEvent
    ) -> tuple[ExperienceKind, str, float, dict[str, Any]] | None:
        """§4/§5: a *verified* shared activity — never an inference.

        Only a real, long-enough session becomes a shared episode; a two-minute
        dabble is not a memory (the threshold is Phase 9's, reused, not
        redefined), and a non-shared social fact belongs to other layers.
        """
        payload = event.payload
        if str(payload.get("interaction_type", "")) != "shared_activity":
            return None
        duration = float(payload.get("duration_minutes", 0.0) or 0.0)
        if duration < MIN_FULFILL_DURATION_MINUTES:
            return None
        person_id = str(event.target_entity_id)
        activity = str(payload.get("target_activity", "") or "") or "活动"
        name = self.commitment_describe(person_id)
        commitment_id = str(payload.get("commitment_id", "") or "")
        significance = str(payload.get("significance", "") or "")
        importance = SHARED_ACTIVITY_BASE_IMPORTANCE
        if commitment_id:
            importance += SHARED_COMMITMENT_BONUS  # a promise actually kept (§9)
        if duration >= SHARED_LONG_MINUTES:
            importance += SHARED_LONG_BONUS
        if significance == "major":
            importance += SHARED_MAJOR_BONUS
        importance = min(0.95, importance)
        summary = f"和{name}一起{activity}了{round(duration)}分钟"
        return (
            ExperienceKind.shared_activity,
            summary,
            importance,
            {
                "interaction_id": str(payload.get("interaction_id", "") or ""),
                "person_id": person_id,
                "name": name,
                "activity": activity,
                "duration_minutes": round(duration, 2),
                "commitment_id": commitment_id,
                "action_id": str(payload.get("action_id", "") or ""),
                "action_instance_id": str(payload.get("action_instance_id", "") or ""),
                "significance": significance,
            },
        )

    def _commitment_outcome(
        self, event: SandboxEvent
    ) -> tuple[ExperienceKind, str, float, dict[str, Any]]:
        """§21/§32: a promise's ending is a lived episode; its birth is not."""
        payload = event.payload
        person = self.commitment_describe(str(payload.get("person_id", "")))
        activity = str(payload.get("target_activity", "")) or str(payload.get("kind", ""))
        kind = str(payload.get("kind", ""))
        if event.event_type is ET.COMMITMENT_FULFILLED:
            summary, importance, outcome = (
                f"履行了与{person}的约定（{activity}）",
                0.75,
                "fulfilled",
            )
        elif event.event_type is ET.COMMITMENT_BROKEN:
            summary, importance, outcome = f"没能履行与{person}的约定（{activity}）", 0.8, "broken"
        else:
            summary, importance, outcome = (
                f"与{person}的约定改期了（{activity}）",
                0.6,
                "rescheduled",
            )
        return (
            ExperienceKind.commitment_outcome,
            summary,
            importance,
            {
                "commitment_id": str(payload.get("commitment_id", "")),
                "person_id": str(payload.get("person_id", "")),
                "name": person,
                "kind": kind,
                "outcome": outcome,
                "description": str(payload.get("description", "")),
            },
        )

    def commitment_describe(self, person_id: str) -> str:
        """Who the promise was with, in words the runtime already owns."""
        manager = getattr(self._rt, "commitments", None)
        if manager is None:
            return person_id or "对方"
        try:
            return manager.person_label(person_id)
        except Exception:  # noqa: BLE001 - a label must never break an experience
            return person_id or "对方"

    def _build(  # noqa: PLR0911 - one branch per experience kind, flat by design
        self, event: SandboxEvent
    ) -> tuple[ExperienceKind, str, float, dict[str, Any]] | None:
        payload = event.payload
        if event.event_type is ET.ACTION_COMPLETED:
            definition = self._rt.actions.definitions.get(event.target_entity_id)
            name = definition.name if definition else event.target_entity_id
            typical = definition.typical_minutes if definition else 0
            detail = str(payload.get("detail", "") or "")
            summary = f"完成了{name}（{detail}）" if detail else f"完成了{name}"
            importance: float = 0.55 if typical >= 20 else 0.4
            return (
                ExperienceKind.action_completed,
                summary,
                importance,
                {
                    "action_name": name,
                    "typical_minutes": typical,
                    # §4: the ActionInstance is the episode identity Phase 10 needs
                    "action_id": str(event.payload.get("action_id", "") or ""),
                    "action_instance_id": str(payload.get("action_instance_id", "") or ""),
                },
            )
        if event.event_type is ET.ACTION_INTERRUPTED:
            definition = self._rt.actions.definitions.get(event.target_entity_id)
            name = definition.name if definition else event.target_entity_id
            reason = str(payload.get("reason", ""))
            return (
                ExperienceKind.action_interrupted,
                f"{name}进行到一半被打断（{reason}）",
                0.6,
                {"action_name": name, "reason": reason, "resumable": payload.get("resumable")},
            )
        if event.event_type is ET.ACTION_RESUMED:
            definition = self._rt.actions.definitions.get(event.target_entity_id)
            name = definition.name if definition else event.target_entity_id
            return (
                ExperienceKind.action_resumed,
                f"继续进行{name}",
                0.4,
                {"action_name": name},
            )
        if event.event_type is ET.INTERACTION_COMPLETED:
            itype = str(payload.get("interaction_type", ""))
            target = event.target_entity_id
            return (
                ExperienceKind.interaction_completed,
                f"与{target}完成了一次{itype}互动",
                0.5,
                {"interaction_type": itype, "target": target},
            )
        if event.event_type is ET.PET_FED:
            pet = self._rt.pet.name if getattr(self._rt, "pet", None) else "宠物"
            food = str(payload.get("food", ""))
            return (
                ExperienceKind.pet_care,
                f"{pet}饿了，已添{food}".rstrip("了"),
                0.55,
                {"pet": pet, "food": food},
            )
        if event.event_type is ET.PROJECT_PROGRESS_CHANGED:
            before = float(payload.get("before", 0.0))
            after = float(payload.get("after", 0.0))
            if not payload.get("completed") and not _milestone_crossed(before, after):
                return None  # routine 0.35 → 0.36 is not a memory (§22)
            project = self._rt.projects.get(event.target_entity_id, {})
            name = str(project.get("name", event.target_entity_id))
            done = bool(payload.get("completed"))
            summary = f"{name}完成了" if done else f"{name}推进到了 {round(after * 100)}%"
            importance = 0.85 if done else 0.7
            return (
                ExperienceKind.project_milestone,
                summary,
                importance,
                {"project": event.target_entity_id, "name": name, "after": after},
            )
        if event.event_type in (
            ET.COMMITMENT_FULFILLED,
            ET.COMMITMENT_BROKEN,
            ET.COMMITMENT_RESCHEDULED,
        ):
            return self._commitment_outcome(event)
        if event.event_type is ET.SOCIAL_INTERACTION:
            return self._shared_activity(event)
        if event.event_type is ET.KNOWLEDGE_CHANGED:
            previous = payload.get("before")
            key = str(payload.get("key", ""))
            if previous is not None:
                return None  # re-learning is normal state upkeep, not an episode
            return (
                ExperienceKind.knowledge_learned,
                f"首次获知：{self._knowledge_label(key)}",
                0.6,
                {"knowledge_key": key},
            )
        if event.event_type is ET.WORLD_EXTERNAL_INFLUENCE:
            actor = str(payload.get("actor", ""))
            return (
                ExperienceKind.external_influence,
                f"{actor or '外部'}的邀请改变了当前安排"
                + (f"（{payload.get('reason', '')}）" if payload.get("reason") else ""),
                0.7,
                {
                    "actor": actor,
                    "semantic_kind": payload.get("semantic_kind", ""),
                },
            )
        if event.event_type is ET.GOAL_COMPLETED:
            description = str(payload.get("description", "") or payload.get("goal_kind", ""))
            return (
                ExperienceKind.goal_completed,
                f"完成目标：{description}",
                0.65,
                {
                    "goal_id": str(payload.get("goal_id", "")),
                    "goal_kind": str(payload.get("goal_kind", "")),
                    "description": description,
                },
            )
        if event.event_type is ET.RELATIONSHIP_CHANGED:
            person = str(payload.get("name") or payload.get("person_id", ""))
            return (
                ExperienceKind.relationship_changed,
                f"与{person}的关系发生了变化（{payload.get('interaction_type', '')}）",
                0.75,
                {
                    "person_id": str(payload.get("person_id", "")),
                    "relation_type": str(payload.get("relation_type", "")),
                    "interaction_type": str(payload.get("interaction_type", "")),
                    "fields": list(payload.get("fields", []) or []),
                },
            )
        if event.event_type is ET.SOCIAL_SPACE_CHANGED:
            fields = payload.get("fields") or []
            only_temperature = fields == ["social_temperature"]
            return (
                ExperienceKind.social_contact,
                f"在{event.target_entity_id}发生了社交活动",
                0.2 if only_temperature else 0.25,
                {"space": event.target_entity_id},
            )
        return None

    @staticmethod
    def _knowledge_label(key: str) -> str:
        """Human-ish label for a knowledge key, never a character literal."""
        return key.replace("_", " ").strip() or "一件事"

    # ---------------------------------------------------------------- drain

    def sample(self, *, clear: bool = True) -> list[ExperienceRecord]:
        """Take the pending experiences (flush path; the audit trail remains)."""
        records = list(self._pending)
        if clear:
            self._pending.clear()
        return records

    def emitted(self, *, limit: int = 64) -> list[ExperienceRecord]:
        """The audit trail (newest last) — replay/dedupe/continuity reads."""
        rows = list(self._emitted)
        return rows[-limit:]

    def pending(self) -> int:
        return len(self._pending)
