"""Experience layer (v2.1 Phase 4 §5-§7): what she actually lived through.

    SandboxEvent → ExperienceBuilder → ExperienceRecord

Experiences are derived from *real* sandbox events only — never generated by
an LLM (§6/§14). The builder is deliberately selective (§7 noise filter):

* business events (action completed/interrupted/resumed, interactions, pet
  fed, external influence, project milestones, first-time knowledge) become
  experiences;
* continuous noise (NEED_CHANGED drift, request/started bookkeeping, routine
  queue traffic) is ignored;
* one behaviour chain (same ``correlation_id``) collapses into **one**
  experience — the pet-feed chain must not produce five near-duplicate rows.

Importance is a deterministic score (§13) computed from the event kind and
its payload; it decides whether the experience can later become a memory
candidate, not whether it is remembered as an experience.
"""

from __future__ import annotations

import uuid
from collections import deque
from enum import Enum
from typing import Any

from pydantic import BaseModel, Field

from app.sandbox.events import SandboxEvent
from app.sandbox.events import SandboxEventType as ET

#: events that may carry experience meaning (§7) — an allow-list, not a
#: deny-list, so new internal events never leak into memory by accident
EXPERIENCE_EVENTS: frozenset[ET] = frozenset(
    {
        ET.ACTION_COMPLETED,
        ET.ACTION_INTERRUPTED,
        ET.ACTION_RESUMED,
        ET.INTERACTION_COMPLETED,
        ET.PET_FED,
        ET.PROJECT_PROGRESS_CHANGED,
        ET.KNOWLEDGE_CHANGED,
        ET.WORLD_EXTERNAL_INFLUENCE,
        ET.SOCIAL_SPACE_CHANGED,
        #: §20: a completed goal may become a memory; creation never does
        ET.GOAL_COMPLETED,
    }
)

#: project progress thresholds that count as milestones (§22/§28-6)
PROJECT_MILESTONES = (0.5, 0.75, 1.0)


class ExperienceKind(str, Enum):  # noqa: UP042 - pydantic-friendly str enum
    action_completed = "action_completed"
    action_interrupted = "action_interrupted"
    action_resumed = "action_resumed"
    interaction_completed = "interaction_completed"
    pet_care = "pet_care"
    project_milestone = "project_milestone"
    knowledge_learned = "knowledge_learned"
    external_influence = "external_influence"
    social_contact = "social_contact"
    goal_completed = "goal_completed"


class ExperienceRecord(BaseModel):
    """One lived-through episode (§5) with full event provenance."""

    id: str
    character_id: str = ""
    timestamp: float = 0.0
    kind: ExperienceKind
    summary: str = ""
    importance: float = Field(default=0.3, ge=0.0, le=1.0)
    location: str = ""
    actors: list[str] = Field(default_factory=list)
    #: every sandbox event id that fed this record (provenance root, §10)
    source_event_ids: list[str] = Field(default_factory=list)
    causation_id: str = ""
    correlation_id: str = ""
    action_id: str = ""
    interaction_type: str = ""
    external_source: str = ""
    metadata: dict[str, Any] = Field(default_factory=dict)


def _milestone_crossed(before: float, after: float) -> bool:
    return any(before < mark <= after for mark in PROJECT_MILESTONES)


class ExperienceBuilder:
    """Event-bus subscriber turning sandbox facts into ExperienceRecords.

    One record per behaviour chain: repeat observations of the same
    ``correlation_id`` merge into the existing record (its ``importance``
    takes the maximum, its kind is upgraded by the priority table below).
    """

    #: higher rank wins when a chain produces several qualifying events
    _KIND_RANK = {
        ExperienceKind.social_contact: 1,
        ExperienceKind.action_resumed: 2,
        ExperienceKind.interaction_completed: 3,
        ExperienceKind.action_completed: 4,
        ExperienceKind.knowledge_learned: 5,
        ExperienceKind.pet_care: 6,
        ExperienceKind.project_milestone: 7,
        ExperienceKind.action_interrupted: 8,
        ExperienceKind.external_influence: 9,
    }

    def __init__(self, runtime: Any, *, clock: Any) -> None:
        self._rt = runtime
        self._clock = clock
        self._pending: list[ExperienceRecord] = []
        #: audit trail of everything emitted (replay/dedupe tests, continuity)
        self._emitted: deque[ExperienceRecord] = deque(maxlen=128)
        self._by_correlation: dict[str, ExperienceRecord] = {}
        self.ignored = 0

    # ------------------------------------------------------------------ bus

    def observe(self, event: SandboxEvent) -> None:
        """Bus handler (sync): qualifying event → experience in the buffer."""
        if event.event_type not in EXPERIENCE_EVENTS:
            self.ignored += 1
            return
        built = self._build(event)
        if built is None:
            self.ignored += 1
            return
        kind, summary, importance, metadata = built
        key = event.correlation_id or event.event_id
        existing = self._by_correlation.get(key)
        if existing is not None:
            existing.source_event_ids.append(event.event_id)
            existing.importance = max(existing.importance, importance)
            if self._KIND_RANK.get(kind, 0) > self._KIND_RANK.get(existing.kind, 0):
                existing.kind = kind
                existing.summary = summary
            existing.metadata.update(metadata)
            return
        record = ExperienceRecord(
            id=f"exp_{uuid.uuid4().hex[:12]}",
            character_id=getattr(self._rt, "character_id", ""),
            timestamp=float(event.timestamp or self._clock()),
            kind=kind,
            summary=summary,
            importance=importance,
            location=self._rt.character.location,
            actors=[actor for actor in (event.source_entity_id, event.target_entity_id) if actor],
            source_event_ids=[event.event_id],
            causation_id=event.causation_id,
            correlation_id=event.correlation_id,
            action_id=str(event.payload.get("action_id", "") or ""),
            interaction_type=str(event.payload.get("interaction_type", "") or ""),
            external_source=str(event.payload.get("source", "") or ""),
            metadata=metadata,
        )
        self._by_correlation[key] = record
        self._pending.append(record)
        self._emitted.append(record)

    # ------------------------------------------------------------ mapping

    def _build(  # noqa: PLR0911 - one branch per experience kind, flat by design
        self, event: SandboxEvent
    ) -> tuple[ExperienceKind, str, float, dict[str, Any]] | None:
        payload = event.payload
        if event.event_type is ET.ACTION_COMPLETED:
            definition = self._rt.actions.definitions.get(event.target_entity_id)
            name = definition.name if definition else event.target_entity_id
            typical = definition.typical_minutes if definition else 0
            detail = str(payload.get("detail", "") or "")
            summary = f"完成了{name}（{detail}）" if detail else f"完成了{name}"
            importance: float = 0.55 if typical >= 20 else 0.4
            return (
                ExperienceKind.action_completed,
                summary,
                importance,
                {"action_name": name, "typical_minutes": typical},
            )
        if event.event_type is ET.ACTION_INTERRUPTED:
            definition = self._rt.actions.definitions.get(event.target_entity_id)
            name = definition.name if definition else event.target_entity_id
            reason = str(payload.get("reason", ""))
            return (
                ExperienceKind.action_interrupted,
                f"{name}进行到一半被打断（{reason}）",
                0.6,
                {"action_name": name, "reason": reason, "resumable": payload.get("resumable")},
            )
        if event.event_type is ET.ACTION_RESUMED:
            definition = self._rt.actions.definitions.get(event.target_entity_id)
            name = definition.name if definition else event.target_entity_id
            return (
                ExperienceKind.action_resumed,
                f"继续进行{name}",
                0.4,
                {"action_name": name},
            )
        if event.event_type is ET.INTERACTION_COMPLETED:
            itype = str(payload.get("interaction_type", ""))
            target = event.target_entity_id
            return (
                ExperienceKind.interaction_completed,
                f"与{target}完成了一次{itype}互动",
                0.5,
                {"interaction_type": itype, "target": target},
            )
        if event.event_type is ET.PET_FED:
            pet = self._rt.pet.name if getattr(self._rt, "pet", None) else "宠物"
            food = str(payload.get("food", ""))
            return (
                ExperienceKind.pet_care,
                f"{pet}饿了，已添{food}".rstrip("了"),
                0.55,
                {"pet": pet, "food": food},
            )
        if event.event_type is ET.PROJECT_PROGRESS_CHANGED:
            before = float(payload.get("before", 0.0))
            after = float(payload.get("after", 0.0))
            if not payload.get("completed") and not _milestone_crossed(before, after):
                return None  # routine 0.35 → 0.36 is not a memory (§22)
            project = self._rt.projects.get(event.target_entity_id, {})
            name = str(project.get("name", event.target_entity_id))
            done = bool(payload.get("completed"))
            summary = f"{name}完成了" if done else f"{name}推进到了 {round(after * 100)}%"
            importance = 0.85 if done else 0.7
            return (
                ExperienceKind.project_milestone,
                summary,
                importance,
                {"project": event.target_entity_id, "name": name, "after": after},
            )
        if event.event_type is ET.KNOWLEDGE_CHANGED:
            previous = payload.get("before")
            key = str(payload.get("key", ""))
            if previous is not None:
                return None  # re-learning is normal state upkeep, not an episode
            return (
                ExperienceKind.knowledge_learned,
                f"首次获知：{self._knowledge_label(key)}",
                0.6,
                {"knowledge_key": key},
            )
        if event.event_type is ET.WORLD_EXTERNAL_INFLUENCE:
            actor = str(payload.get("actor", ""))
            return (
                ExperienceKind.external_influence,
                f"{actor or '外部'}的邀请改变了当前安排"
                + (f"（{payload.get('reason', '')}）" if payload.get("reason") else ""),
                0.7,
                {
                    "actor": actor,
                    "semantic_kind": payload.get("semantic_kind", ""),
                },
            )
        if event.event_type is ET.GOAL_COMPLETED:
            description = str(payload.get("description", "") or payload.get("goal_kind", ""))
            return (
                ExperienceKind.goal_completed,
                f"完成目标：{description}",
                0.65,
                {
                    "goal_id": str(payload.get("goal_id", "")),
                    "goal_kind": str(payload.get("goal_kind", "")),
                    "description": description,
                },
            )
        if event.event_type is ET.SOCIAL_SPACE_CHANGED:
            fields = payload.get("fields") or []
            only_temperature = fields == ["social_temperature"]
            return (
                ExperienceKind.social_contact,
                f"在{event.target_entity_id}发生了社交活动",
                0.2 if only_temperature else 0.25,
                {"space": event.target_entity_id},
            )
        return None

    @staticmethod
    def _knowledge_label(key: str) -> str:
        """Human-ish label for a knowledge key, never a character literal."""
        return key.replace("_", " ").strip() or "一件事"

    # ---------------------------------------------------------------- drain

    def sample(self, *, clear: bool = True) -> list[ExperienceRecord]:
        """Take the pending experiences (flush path; the audit trail remains)."""
        records = list(self._pending)
        if clear:
            self._pending.clear()
        return records

    def emitted(self, *, limit: int = 64) -> list[ExperienceRecord]:
        """The audit trail (newest last) — replay/dedupe/continuity reads."""
        rows = list(self._emitted)
        return rows[-limit:]

    def pending(self) -> int:
        return len(self._pending)
